### ISSUE TITLE
KindError: No implementation for kind 'Person'

### ISSUE THREAD

**Issue by ianw** [dound/gae-sessions#19]
I see the following backtrace semi-occasionally -- I think it happens with a stale cookie but I haven't really traced it down.  Any suggestions?

<pre>
ERROR:root:Exception encountered handling request
Traceback (most recent call last):
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 3245, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 3186, in _Dispatch
    base_env_dict=env_dict)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 531, in Dispatch
    base_env_dict=base_env_dict)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 2410, in Dispatch
    self._module_dict)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 2320, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/tools/dev_appserver.py", line 2216, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "/home/ianw/programs/easygeotag-svn/main.py", line 52, in <module>
    main()
  File "/home/ianw/programs/easygeotag-svn/main.py", line 49, in main
    util.run_wsgi_app(application)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/ext/webapp/util.py", line 97, in run_wsgi_app
    run_bare_wsgi_app(add_wsgi_middleware(application))
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/ext/webapp/util.py", line 115, in run_bare_wsgi_app
    result = application(env, _start_response)
  File "/home/ianw/programs/easygeotag-svn/django.zip/django/core/handlers/wsgi.py", line 241, in __call__
  File "/home/ianw/programs/easygeotag-svn/django.zip/django/core/handlers/base.py", line 76, in get_response
  File "/home/ianw/programs/easygeotag-svn/gaesessions/__init__.py", line 462, in process_request
    self.response_handler = self.wrapped_wsgi_middleware(None, lambda status, headers, exc_info : headers)
  File "/home/ianw/programs/easygeotag-svn/gaesessions/__init__.py", line 438, in __call__
    _current_session = Session(lifetime=self.lifetime, no_datastore=self.no_datastore, cookie_only_threshold=self.cookie_only_thresh, cookie_key=self.cookie_key)
  File "/home/ianw/programs/easygeotag-svn/gaesessions/__init__.py", line 70, in __init__
    self.__read_cookie()
  File "/home/ianw/programs/easygeotag-svn/gaesessions/__init__.py", line 99, in __read_cookie
    self.data = self.__decode_data(pdump)
  File "/home/ianw/programs/easygeotag-svn/gaesessions/__init__.py", line 192, in __decode_data
    eO[k] = db.model_from_protobuf(v)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/ext/db/__init__.py", line 332, in model_from_protobuf
    return class_for_kind(entity.kind()).from_entity(entity)
  File "/home/ianw/programs/easygeotag-svn/.google_appengine/google/appengine/ext/db/__init__.py", line 266, in class_for_kind
    raise KindError('No implementation for kind \'%s\'' % kind)
KindError: No implementation for kind 'Person'
</pre>

**Comment by dound** [comment]
It sounds like you are trying to load a `Person` entity from a session without importing the `Person` model first.

To ensure that `Person` is available when the session middleware runs,  you must import the `Person` model in your main.py script (assuming the usual GAE project setup).  Otherwise, if a fresh instance of your app  is spun up by GAE, then it might not have imported the `Person` model before the sessions library tries to convert a protobuf representing a `Person` entity into an actual Python `Person` instance (leading to the `KindError` you're experiencing). 

~ David

**Comment by ianw** [comment]
The thing is it works most of the time.  Just sometimes I seem to get this error, both locally and on the actual app server.

It just happened when I uploaded a new version to GAE and reloaded the page, for example.  I cleared the cookie and it started working again.  I can't see what path it's taking in some cases where 'Person' isn't available...

**Comment by ianw** [comment]
Oh, wait, I see what you're saying sorry, my 'main.py'.  That makes sense.  This is probably invalid, maybe a note on this in the readme might help others
